function battery_app_gui
% BATTERY_APP_GUI Functional prototype for battery data visualization.
% Week 4 deliverables:
%   - SOC / Voltage / Current / Temperature vs time plotting
%   - basic time-range selection
% Week 5 deliverables:
%   - Load CSV button
%   - Generate synthetic data button
%   - Plot display area
%   - Plot selection dropdown
% Week 6 deliverables:
%   - Battery summary dashboard panel
%   - Min/max voltage, max temperature, average current
%   - SOC start/end metrics for the displayed time range

dataTable = table();
textColor = [0.00, 0.00, 0.00];
inputBackgroundColor = [1.00, 1.00, 1.00];
buttonColor = [0.00, 0.45, 0.74];
buttonTextColor = [1.00, 1.00, 1.00];
summaryPanelColor = [1.00, 1.00, 1.00];

fig = uifigure( ...
    "Name", "Battery Data Visualizer", ...
    "Position", [100, 100, 1120, 680], ...
    "Color", [0.97, 0.97, 0.98]);

uibutton(fig, "push", ...
    "Text", "Load CSV", ...
    "Position", [20, 635, 110, 32], ...
    "BackgroundColor", buttonColor, ...
    "FontColor", buttonTextColor, ...
    "ButtonPushedFcn", @onLoadCsv);

uibutton(fig, "push", ...
    "Text", "Generate Synthetic Data", ...
    "Position", [145, 635, 180, 32], ...
    "BackgroundColor", buttonColor, ...
    "FontColor", buttonTextColor, ...
    "ButtonPushedFcn", @onGenerateSynthetic);

uilabel(fig, ...
    "Text", "Plot:", ...
    "Position", [350, 640, 35, 22], ...
    "FontColor", textColor);

plotDropdown = uidropdown(fig, ...
    "Items", { ...
        'SOC vs Time', ...
        'Voltage vs Time', ...
        'Current vs Time', ...
        'Temperature vs Time'}, ...
    "Value", 'SOC vs Time', ...
    "Position", [390, 635, 180, 32], ...
    "BackgroundColor", inputBackgroundColor, ...
    "FontColor", textColor, ...
    "ValueChangedFcn", @onControlsChanged);

uilabel(fig, ...
    "Text", "Start Time (s):", ...
    "Position", [590, 640, 92, 22], ...
    "FontColor", textColor);

startTimeField = uieditfield(fig, "numeric", ...
    "Position", [686, 635, 95, 32], ...
    "BackgroundColor", inputBackgroundColor, ...
    "FontColor", textColor, ...
    "ValueChangedFcn", @onControlsChanged);

uilabel(fig, ...
    "Text", "End Time (s):", ...
    "Position", [798, 640, 85, 22], ...
    "FontColor", textColor);

endTimeField = uieditfield(fig, "numeric", ...
    "Position", [886, 635, 95, 32], ...
    "BackgroundColor", inputBackgroundColor, ...
    "FontColor", textColor, ...
    "ValueChangedFcn", @onControlsChanged);

uibutton(fig, "push", ...
    "Text", "Full Range", ...
    "Position", [994, 635, 100, 32], ...
    "BackgroundColor", buttonColor, ...
    "FontColor", buttonTextColor, ...
    "ButtonPushedFcn", @onResetRange);

plotAxes = uiaxes(fig, ...
    "Position", [20, 90, 780, 525], ...
    "Color", inputBackgroundColor, ...
    "Box", "on");
grid(plotAxes, "on");
title(plotAxes, "Load CSV or generate synthetic data to begin");
xlabel(plotAxes, "Time (s)");
ylabel(plotAxes, "Value");
stylePlotAxes();

summaryPanel = uipanel(fig, ...
    "Title", "Battery Summary", ...
    "Position", [820, 90, 274, 525], ...
    "BackgroundColor", summaryPanelColor, ...
    "ForegroundColor", textColor);

summaryRangeLabel = uilabel(summaryPanel, ...
    "Text", "Displayed Range: --", ...
    "Position", [18, 470, 238, 24], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "Min Voltage", ...
    "Position", [18, 420, 120, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
minVoltageValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 392, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "Max Voltage", ...
    "Position", [18, 350, 120, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
maxVoltageValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 322, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "Max Temperature", ...
    "Position", [18, 280, 140, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
maxTemperatureValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 252, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "Average Current", ...
    "Position", [18, 210, 140, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
avgCurrentValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 182, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "SOC Start", ...
    "Position", [18, 140, 120, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
socStartValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 112, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

uilabel(summaryPanel, ...
    "Text", "SOC End", ...
    "Position", [18, 70, 120, 20], ...
    "FontWeight", "bold", ...
    "FontColor", textColor);
socEndValueLabel = uilabel(summaryPanel, ...
    "Text", "--", ...
    "Position", [18, 42, 220, 24], ...
    "FontSize", 16, ...
    "FontColor", textColor);

statusLabel = uilabel(fig, ...
    "Text", "Ready.", ...
    "Position", [20, 30, 1074, 30], ...
    "HorizontalAlignment", "left", ...
    "FontColor", textColor);

tryLoadDefaultSample();

    function tryLoadDefaultSample
        samplePath = fullfile(pwd, 'sample_battery_data.csv');
        if ~isfile(samplePath)
            return;
        end

        try
            loadedTable = readtable(samplePath);
            dataTable = normalize_battery_table(loadedTable);
            syncTimeControlsToData();
            updatePlot();
            statusLabel.Text = "Loaded default sample_battery_data.csv";
        catch
            % Ignore preload errors; user can load/generate manually.
        end
    end

    function onLoadCsv(~, ~)
        [fileName, filePath] = uigetfile("*.csv", "Select Battery CSV");
        if isequal(fileName, 0)
            statusLabel.Text = "CSV load canceled.";
            return;
        end

        fullPath = fullfile(filePath, fileName);

        try
            loadedTable = readtable(fullPath);
            dataTable = normalize_battery_table(loadedTable);
            syncTimeControlsToData();
            updatePlot();
            statusLabel.Text = sprintf("Loaded: %s", fullPath);
        catch ME
            uialert(fig, ME.message, "CSV Load Error");
            statusLabel.Text = "Failed to load CSV.";
        end
    end

    function onGenerateSynthetic(~, ~)
        outputPath = fullfile(pwd, 'sample_battery_data.csv');

        try
            generatedTable = randomized_data_generator(outputPath, false);
            dataTable = normalize_battery_table(generatedTable);
            syncTimeControlsToData();
            updatePlot();
            statusLabel.Text = sprintf("Generated synthetic data: %s", outputPath);
        catch ME
            uialert(fig, ME.message, "Generation Error");
            statusLabel.Text = "Synthetic data generation failed.";
        end
    end

    function onControlsChanged(~, ~)
        if isempty(dataTable)
            return;
        end
        updatePlot();
    end

    function onResetRange(~, ~)
        if isempty(dataTable)
            return;
        end
        syncTimeControlsToData();
        updatePlot();
    end

    function syncTimeControlsToData
        tMin = dataTable.Time_s(1);
        tMax = dataTable.Time_s(end);

        if tMax <= tMin
            tMax = tMin + 1;
        end

        startTimeField.Limits = [tMin, tMax];
        endTimeField.Limits = [tMin, tMax];
        startTimeField.Value = tMin;
        endTimeField.Value = tMax;
    end

    function updatePlot
        if isempty(dataTable)
            cla(plotAxes);
            title(plotAxes, "Load CSV or generate synthetic data to begin");
            xlabel(plotAxes, "Time (s)");
            ylabel(plotAxes, "Value");
            stylePlotAxes();
            resetSummaryMetrics();
            return;
        end

        selectedRange = [startTimeField.Value, endTimeField.Value];
        if selectedRange(1) > selectedRange(2)
            selectedRange = fliplr(selectedRange);
            startTimeField.Value = selectedRange(1);
            endTimeField.Value = selectedRange(2);
        end

        appliedRange = battery_visualization(plotAxes, dataTable, plotDropdown.Value, selectedRange);
        stylePlotAxes();
        updateSummaryMetrics(appliedRange);

        statusLabel.Text = sprintf( ...
            "Displaying %s (%.1f s to %.1f s)", ...
            plotDropdown.Value, appliedRange(1), appliedRange(2));
    end

    function stylePlotAxes
        plotAxes.XColor = textColor;
        plotAxes.YColor = textColor;
        plotAxes.Title.Color = textColor;
        plotAxes.XLabel.Color = textColor;
        plotAxes.YLabel.Color = textColor;
    end

    function updateSummaryMetrics(appliedRange)
        if isempty(dataTable)
            resetSummaryMetrics();
            return;
        end

        mask = (dataTable.Time_s >= appliedRange(1)) & ...
               (dataTable.Time_s <= appliedRange(2));

        if ~any(mask)
            mask = true(height(dataTable), 1);
            appliedRange = [dataTable.Time_s(1), dataTable.Time_s(end)];
        end

        displayedData = dataTable(mask, :);

        summaryRangeLabel.Text = sprintf( ...
            "Displayed Range: %.1f s to %.1f s", ...
            appliedRange(1), appliedRange(2));
        minVoltageValueLabel.Text = sprintf("%.2f V", min(displayedData.PackVoltage_V));
        maxVoltageValueLabel.Text = sprintf("%.2f V", max(displayedData.PackVoltage_V));
        maxTemperatureValueLabel.Text = sprintf("%.2f C", max(displayedData.Temperature_C));
        avgCurrentValueLabel.Text = sprintf("%.2f A", mean(displayedData.Current_A));
        socStartValueLabel.Text = sprintf("%.2f %%", displayedData.SOC_pct(1));
        socEndValueLabel.Text = sprintf("%.2f %%", displayedData.SOC_pct(end));
    end

    function resetSummaryMetrics
        summaryRangeLabel.Text = "Displayed Range: --";
        minVoltageValueLabel.Text = "--";
        maxVoltageValueLabel.Text = "--";
        maxTemperatureValueLabel.Text = "--";
        avgCurrentValueLabel.Text = "--";
        socStartValueLabel.Text = "--";
        socEndValueLabel.Text = "--";
    end
end
